# Generated by Django 4.2.1 on 2023-05-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_anulate_alter_departamento_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Áreas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
