# Generated by Django 4.2.1 on 2023-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'TECNICO'), ('4', 'OTRO')], max_length=1, null=True, verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
